/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * Information about Wild Apricot account
 * @param Id Account unique identifier.
 * @param Name The account name. This corresponds to the organization name as it appears on the Organization details screen.
 * @param Url
 * @param PrimaryDomainName The primary domain name for the account.
 * @param IsFreeAccount
 * @param Resources Collection of account-related resources.
 * @param ContactLimitInfo
 * @param TimeZone
 * @param Currency
 * @param Localization
 * @param SquareRegisterSettings
 * @param PaymentSettings
 * @param BillingPlan
 */
data class Account(
    /* Account unique identifier. */
    val Id: kotlin.Int,
    /* The account name. This corresponds to the organization name as it appears on the Organization details screen. */
    val Name: kotlin.String,
    /* The primary domain name for the account. */
    val PrimaryDomainName: kotlin.String,
    val ContactLimitInfo: ContactLimitInfo,
    val Currency: Currency,
    val Localization: Localization,
    val SquareRegisterSettings: SquareRegisterSettings,
    val Url: ResourceUrl? = null,
    val IsFreeAccount: kotlin.Boolean? = null,
    /* Collection of account-related resources. */
    val Resources: kotlin.Array<Resource>? = null,
    val TimeZone: TimeZone? = null,
    val PaymentSettings: PaymentSettings? = null,
    val BillingPlan: BillingPlan? = null
) {

}

