/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param ObjectType Object type which was requested. In this case it is always Contact.
 * @param FilterExpression Value of $filter parameter passed into API.
 * @param SelectExpression Value of $select parameter passed into API.
 * @param ReturnIds Indicates if client requested only a list of identifiers, instead of full list of contacts.
 */
data class ContactsAsyncResponseInitialQuery(
    /* Object type which was requested. In this case it is always Contact. */
    val ObjectType: kotlin.String? = null,
    /* Value of $filter parameter passed into API. */
    val FilterExpression: kotlin.String? = null,
    /* Value of $select parameter passed into API. */
    val SelectExpression: kotlin.String? = null,
    /* Indicates if client requested only a list of identifiers, instead of full list of contacts. */
    val ReturnIds: kotlin.Boolean? = null
) {

}

