/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Value Payment amount.
 * @param DocumentDate Document date.
 * @param Invoices If not null or empty then invoices with these IDs will be settled to new payment.
 * @param Contact
 * @param Tender
 * @param Comment Internal note on payment. Visible to administrators only.
 * @param PublicComment Comment to payor. Visible to both administrators and payor.
 * @param PaymentType
 */
data class CreatePaymentModel(
    /* Payment amount. */
    val Value: kotlin.Float? = null,
    /* Document date. */
    val DocumentDate: java.time.LocalDateTime? = null,
    /* If not null or empty then invoices with these IDs will be settled to new payment. */
    val Invoices: kotlin.Array<LinkedResource>? = null,
    val Contact: BundleAdministrator? = null,
    val Tender: LinkedResource? = null,
    /* Internal note on payment. Visible to administrators only. */
    val Comment: kotlin.String? = null,
    /* Comment to payor. Visible to both administrators and payor. */
    val PublicComment: kotlin.String? = null,
    val PaymentType: PaymentType? = null
) {

}

