/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param FieldName New field name. Must be unique.
 * @param IsRequired Indicates whether a field has to be filled before the form is submitted. This limitation affects member-facing functionality only, admin always can submit form even without required fields.
 * @param AdminOnly Indicates that the field is accessible only by administrators.
 * @param Access
 * @param FieldInstructions Shown as a tip when members or visitors fill in forms. Max length is 250 characters.
 * @param Order Sorting order to display the field in UI.
 * @param AllowedValues List of allowed values for this field. This data is used for Choice and MultipleChoice fields, otherwise it will be ignored.
 * @param RulesAndTermsInfo
 * @param ExistsInLevels Collection of membership levels where the field exists. If empty collection provided, it means the field would be available for all levels.
 * @param MemberAccess
 * @param RenewalPolicy
 * @param ProrateInApplication Whether the cost should be prorated over a partial period of time. Used only by fields with an associated cost.
 * @param ExtraCharge
 */
data class EditContactFieldParams(
    /* New field name. Must be unique. */
    val FieldName: kotlin.String,
    /* Indicates whether a field has to be filled before the form is submitted. This limitation affects member-facing functionality only, admin always can submit form even without required fields. */
    val IsRequired: kotlin.Boolean? = null,
    /* Indicates that the field is accessible only by administrators. */
    val AdminOnly: kotlin.Boolean? = null,
    val Access: ContactFieldAccessLevel? = null,
    /* Shown as a tip when members or visitors fill in forms. Max length is 250 characters. */
    val FieldInstructions: kotlin.String? = null,
    /* Sorting order to display the field in UI. */
    val Order: kotlin.Int? = null,
    /* List of allowed values for this field. This data is used for Choice and MultipleChoice fields, otherwise it will be ignored. */
    val AllowedValues: kotlin.Array<OptionsListItem>? = null,
    val RulesAndTermsInfo: RulesAndTermsInfo? = null,
    /* Collection of membership levels where the field exists. If empty collection provided, it means the field would be available for all levels. */
    val ExistsInLevels: kotlin.Array<EditContactFieldParamsExistsInLevels>? = null,
    val MemberAccess: MemberFieldAccess? = null,
    val RenewalPolicy: RenewalPolicy? = null,
    /* Whether the cost should be prorated over a partial period of time. Used only by fields with an associated cost. */
    val ProrateInApplication: kotlin.Boolean? = null,
    val ExtraCharge: ExtraCharge? = null
) {

}

