/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


import com.squareup.moshi.Json

/**
 * The reason why the email was sent.
 * Values: unknown,memberApplicationActivationEmail,memberApplicationInitiationEmail,memberApplicationBundleMemberActivationEmail,memberApplicationBundleAdminActivationEmail,memberRenewalFreeRenewal,memberRenewalRenewalPending,memberRenewalRenewalConfirmed,memberRenewalRenewalCanceledByMember,memberRenewalMemberRenewalRecurringRenewalFailed,memberRenewalOnlinePaymentSuccessfull,memberRenewalAdvanceRenewalReminder1,memberRenewalAdvanceRenewalReminder2,memberRenewalRenewalDateNotice,memberRenewalGracePeriod,memberRenewalLapsed,memberLevelChangeInitiationEmail,memberLevelChangeActivationEmail,donationConfirmation,eventRegistrationOfflinePaymentFreeLevelConfirmationEmail,eventRegistrationOfflinePaymentPaidLevelConfirmationEmail,eventRegistrationOfflinePaymentPaidLevelPendingEmail,eventRegistrationNewWaitlistEntryEmail,eventRegistrationCanceledEmail,eventRegistrationOnlinePaymentPaidLevelConfirmationEmail,eventRegistrationReminder1,eventRegistrationReminder2,eventRegistrationReminder3,eventRegistrationAnnouncement1,eventRegistrationAnnouncement2,eventRegistrationAnnouncement3,emailBlastMembers,emailBlastRegistrations,emailBlastWaitlistPersons,financesInvoice,financesPaymentReceipt,financesDonationReceipt,financesRefundNote,contactPassword,subscriptionFormConfirmation,publicMemberToMemberEmail,pollAnnouncementNotification,forgottenPasswordRequest,forumNotification,forumTopicNotification,onlineStoreOrder
 */
enum class EmailType(val value: kotlin.String) {

    @Json(name = "Unknown")
    unknown("Unknown"),

    @Json(name = "MemberApplication_ActivationEmail")
    memberApplicationActivationEmail("MemberApplication_ActivationEmail"),

    @Json(name = "MemberApplication_InitiationEmail")
    memberApplicationInitiationEmail("MemberApplication_InitiationEmail"),

    @Json(name = "MemberApplication_BundleMember_ActivationEmail")
    memberApplicationBundleMemberActivationEmail("MemberApplication_BundleMember_ActivationEmail"),

    @Json(name = "MemberApplication_BundleAdmin_ActivationEmail")
    memberApplicationBundleAdminActivationEmail("MemberApplication_BundleAdmin_ActivationEmail"),

    @Json(name = "MemberRenewal_FreeRenewal")
    memberRenewalFreeRenewal("MemberRenewal_FreeRenewal"),

    @Json(name = "MemberRenewal_RenewalPending")
    memberRenewalRenewalPending("MemberRenewal_RenewalPending"),

    @Json(name = "MemberRenewal_RenewalConfirmed")
    memberRenewalRenewalConfirmed("MemberRenewal_RenewalConfirmed"),

    @Json(name = "MemberRenewal_RenewalCanceledByMember")
    memberRenewalRenewalCanceledByMember("MemberRenewal_RenewalCanceledByMember"),

    @Json(name = "MemberRenewal_MemberRenewal_RecurringRenewalFailed")
    memberRenewalMemberRenewalRecurringRenewalFailed("MemberRenewal_MemberRenewal_RecurringRenewalFailed"),

    @Json(name = "MemberRenewal_Online_PaymentSuccessfull")
    memberRenewalOnlinePaymentSuccessfull("MemberRenewal_Online_PaymentSuccessfull"),

    @Json(name = "MemberRenewal_AdvanceRenewalReminder1")
    memberRenewalAdvanceRenewalReminder1("MemberRenewal_AdvanceRenewalReminder1"),

    @Json(name = "MemberRenewal_AdvanceRenewalReminder2")
    memberRenewalAdvanceRenewalReminder2("MemberRenewal_AdvanceRenewalReminder2"),

    @Json(name = "MemberRenewal_RenewalDateNotice")
    memberRenewalRenewalDateNotice("MemberRenewal_RenewalDateNotice"),

    @Json(name = "MemberRenewal_GracePeriod")
    memberRenewalGracePeriod("MemberRenewal_GracePeriod"),

    @Json(name = "MemberRenewal_Lapsed")
    memberRenewalLapsed("MemberRenewal_Lapsed"),

    @Json(name = "MemberLevelChange_InitiationEmail")
    memberLevelChangeInitiationEmail("MemberLevelChange_InitiationEmail"),

    @Json(name = "MemberLevelChange_ActivationEmail")
    memberLevelChangeActivationEmail("MemberLevelChange_ActivationEmail"),

    @Json(name = "Donation_Confirmation")
    donationConfirmation("Donation_Confirmation"),

    @Json(name = "EventRegistration_OfflinePayment_FreeLevelConfirmationEmail")
    eventRegistrationOfflinePaymentFreeLevelConfirmationEmail("EventRegistration_OfflinePayment_FreeLevelConfirmationEmail"),

    @Json(name = "EventRegistration_OfflinePayment_PaidLevelConfirmationEmail")
    eventRegistrationOfflinePaymentPaidLevelConfirmationEmail("EventRegistration_OfflinePayment_PaidLevelConfirmationEmail"),

    @Json(name = "EventRegistration_OfflinePayment_PaidLevelPendingEmail")
    eventRegistrationOfflinePaymentPaidLevelPendingEmail("EventRegistration_OfflinePayment_PaidLevelPendingEmail"),

    @Json(name = "EventRegistration_NewWaitlistEntryEmail")
    eventRegistrationNewWaitlistEntryEmail("EventRegistration_NewWaitlistEntryEmail"),

    @Json(name = "EventRegistration_CanceledEmail")
    eventRegistrationCanceledEmail("EventRegistration_CanceledEmail"),

    @Json(name = "EventRegistration_OnlinePayment_PaidLevelConfirmationEmail")
    eventRegistrationOnlinePaymentPaidLevelConfirmationEmail("EventRegistration_OnlinePayment_PaidLevelConfirmationEmail"),

    @Json(name = "EventRegistration_Reminder1")
    eventRegistrationReminder1("EventRegistration_Reminder1"),

    @Json(name = "EventRegistration_Reminder2")
    eventRegistrationReminder2("EventRegistration_Reminder2"),

    @Json(name = "EventRegistration_Reminder3")
    eventRegistrationReminder3("EventRegistration_Reminder3"),

    @Json(name = "EventRegistration_Announcement1")
    eventRegistrationAnnouncement1("EventRegistration_Announcement1"),

    @Json(name = "EventRegistration_Announcement2")
    eventRegistrationAnnouncement2("EventRegistration_Announcement2"),

    @Json(name = "EventRegistration_Announcement3")
    eventRegistrationAnnouncement3("EventRegistration_Announcement3"),

    @Json(name = "EmailBlast_Members")
    emailBlastMembers("EmailBlast_Members"),

    @Json(name = "EmailBlast_Registrations")
    emailBlastRegistrations("EmailBlast_Registrations"),

    @Json(name = "EmailBlast_WaitlistPersons")
    emailBlastWaitlistPersons("EmailBlast_WaitlistPersons"),

    @Json(name = "Finances_Invoice")
    financesInvoice("Finances_Invoice"),

    @Json(name = "Finances_PaymentReceipt")
    financesPaymentReceipt("Finances_PaymentReceipt"),

    @Json(name = "Finances_DonationReceipt")
    financesDonationReceipt("Finances_DonationReceipt"),

    @Json(name = "Finances_RefundNote")
    financesRefundNote("Finances_RefundNote"),

    @Json(name = "Contact_Password")
    contactPassword("Contact_Password"),

    @Json(name = "SubscriptionForm_Confirmation")
    subscriptionFormConfirmation("SubscriptionForm_Confirmation"),

    @Json(name = "Public_MemberToMemberEmail")
    publicMemberToMemberEmail("Public_MemberToMemberEmail"),

    @Json(name = "Poll_Announcement_Notification")
    pollAnnouncementNotification("Poll_Announcement_Notification"),

    @Json(name = "ForgottenPasswordRequest")
    forgottenPasswordRequest("ForgottenPasswordRequest"),

    @Json(name = "ForumNotification")
    forumNotification("ForumNotification"),

    @Json(name = "ForumTopicNotification")
    forumTopicNotification("ForumTopicNotification"),

    @Json(name = "OnlineStore_Order")
    onlineStoreOrder("OnlineStore_Order");

}

