/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Id Unique identifier of event registration
 * @param Url
 * @param Event
 * @param Contact
 * @param RegistrationTypeId Unique identifier of event registration type
 * @param GuestRegistrationsSummary
 * @param IsCheckedIn Indicates if registrant is already checked in on event.
 * @param RegistrationFields A collection of registration fields values
 * @param ShowToPublic Indicates whether this registration can be shown to other event registrants.
 * @param RegistrationDate Date and time when registration was created. (Account local time)
 * @param Memo Some additional notes about this registration.
 * @param RecreateInvoice Optional boolean value. If specified and equals true, related invoice will be automatically updated (or created) to match selected registration type and extra cost options.
 */
data class EventRegistrationPost(
    val Event: EventRegistrationPostEvent,
    val Contact: EventRegistrationPostEvent,
    /* Unique identifier of event registration type */
    val RegistrationTypeId: kotlin.Int,
    /* Unique identifier of event registration */
    val Id: kotlin.Int? = null,
    val Url: ResourceUrl? = null,
    val GuestRegistrationsSummary: GuestRegistrationsSummary? = null,
    /* Indicates if registrant is already checked in on event. */
    val IsCheckedIn: kotlin.Boolean? = null,
    /* A collection of registration fields values */
    val RegistrationFields: kotlin.Array<FieldValue>? = null,
    /* Indicates whether this registration can be shown to other event registrants. */
    val ShowToPublic: kotlin.Boolean? = null,
    /* Date and time when registration was created. (Account local time) */
    val RegistrationDate: kotlin.String? = null,
    /* Some additional notes about this registration. */
    val Memo: kotlin.String? = null,
    /* Optional boolean value. If specified and equals true, related invoice will be automatically updated (or created) to match selected registration type and extra cost options. */
    val RecreateInvoice: kotlin.Boolean? = null
) {

}

