/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


import com.squareup.moshi.Json

/**
 * Describes event registration status
 * Values: undefined,paid,unpaid,partiallyPaid,canceled,free,noInvoice,onWaitlist
 */
enum class EventRegistrationStatus(val value: kotlin.String) {

    @Json(name = "Undefined")
    undefined("Undefined"),

    @Json(name = "Paid")
    paid("Paid"),

    @Json(name = "Unpaid")
    unpaid("Unpaid"),

    @Json(name = "PartiallyPaid")
    partiallyPaid("PartiallyPaid"),

    @Json(name = "Canceled")
    canceled("Canceled"),

    @Json(name = "Free")
    free("Free"),

    @Json(name = "NoInvoice")
    noInvoice("NoInvoice"),

    @Json(name = "OnWaitlist")
    onWaitlist("OnWaitlist");

}

