/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param Id Unique event session identifier.
 * @param Title Automatically generated session title.
 * @param StartDate Date and time when the event session is scheduled to start.
 * @param StartTimeSpecified Indicates if session start time is specified. False means that StartDate contains only date component.
 * @param EndDate Date and time when the event session is scheduled to end. Could be empty.
 * @param EndTimeSpecified Indicates if session end time is specified. False means that EndDate contains only date component.
 */


data class EventSesssion(
    /* Unique event session identifier. */
    val Id: kotlin.Int? = null,
    /* Automatically generated session title. */
    val Title: kotlin.String? = null,
    /* Date and time when the event session is scheduled to start. */
    val StartDate: kotlin.String? = null,
    /* Indicates if session start time is specified. False means that StartDate contains only date component. */
    val StartTimeSpecified: kotlin.Boolean? = null,
    /* Date and time when the event session is scheduled to end. Could be empty. */
    val EndDate: kotlin.String? = null,
    /* Indicates if session end time is specified. False means that EndDate contains only date component. */
    val EndTimeSpecified: kotlin.Boolean? = null
) {

}

