/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import com.squareup.moshi.Json

/**
 *
 * @param Kind Indicated is the field is common for all contacts or custom for the event.
 */
data class EventRegistrationFieldDescription(
    /* Field name title, could be displayed in user interface. Field name could be changed by account administrator. */
    val FieldName: kotlin.String,
    /* System-defined description of the field. Empty for custom fields. */
    val Description: kotlin.String,
    val FieldType: CustomFieldType,
    /* Indicated is the field is common for all contacts or custom for the event. */
    val kind: EventRegistrationFieldDescription.Kind? = null,
    /* System-defined code associated with field. It does not change even if FieldName is edited in admin backend. */
    val SystemCode: kotlin.String? = null,
    /* Optional hint, which tells how to display and edit field. It appears for String and Choice fields. */
    val DisplayType: kotlin.String? = null,
    /* Field is system-defined and could not be deleted. However, field name could be changed by account administrator. */
    val IsSystem: kotlin.Boolean? = null,
    /* Admin-defined comment for the field. Shown as a tip when members or visitors fill in forms. */
    val FieldInstructions: kotlin.String? = null,
    /* If field value is limited to set of predefined values, this contains list of allowed values. Normally, AllowedValues appear for MultipleChoice and Choice fields. */
    val AllowedValues: kotlin.Array<OptionsListItem>? = null,
    /* Sorting order to display the field in UI */
    val Order: kotlin.Int? = null,
    val RulesAndTermsInfo: RulesAndTermsInfo? = null,
    val ExtraCharge: ExtraCharge? = null,
    /* Indicated is the field is common for all contacts or custom for the event. */

) {

    /**
     * Indicated is the field is common for all contacts or custom for the event.
     * Values: common,custom
     */
    enum class Kind(val value: kotlin.String) {

        @Json(name = "Common")
        common("Common"),

        @Json(name = "Custom")
        custom("Custom");

    }

}

