/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


import com.squareup.moshi.Json

/**
 *  Event accessability.   - Public means event accessible for everyone   - AdminOnly means event accessible for administrators only   - Restricted means event accessible for specific membership levels or groups.
 * Values: `public`,adminOnly,restricted
 */
enum class EventAccessLevel(val value: kotlin.String) {

    @Json(name = "Public")
    `public`("Public"),

    @Json(name = "AdminOnly")
    adminOnly("AdminOnly"),

    @Json(name = "Restricted")
    restricted("Restricted");

}

