/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Id Event identifier.
 * @param Url Event Url to get event details from API.
 * @param Name Event title.
 * @param StartDate Date and time when the event is scheduled to start.
 * @param EndDate Date and time when the event is scheduled to end. Could be empty.
 * @param Location Location where the event will take place.
 */
data class EventStub(
    /* Event identifier. */
    val Id: kotlin.Int? = null,
    /* Event Url to get event details from API. */
    val Url: ResourceUrl? = null,
    /* Event title. */
    val Name: kotlin.String? = null,
    /* Date and time when the event is scheduled to start. */
    val StartDate: kotlin.String? = null,
    /* Date and time when the event is scheduled to end. Could be empty. */
    val EndDate: kotlin.String? = null,
    /* Location where the event will take place. */
    val Location: kotlin.String? = null
) {

}

