/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Application approval policy
 * @param PrepayRequired If true, membership fee should be received in full before application is activated. Else, approved memberships activate immediately, regardless of payment status.
 * @param AdminApprovalRequired  Indicates that account administrator should approve membership application. False means that all applications are considered approved when they are submitted.
 */
data class MembershipRenewalPeriodApplicationReview(
    /* If true, membership fee should be received in full before application is activated. Else, approved memberships activate immediately, regardless of payment status. */
    val PrepayRequired: kotlin.Boolean? = null,
    /*  Indicates that account administrator should approve membership application. False means that all applications are considered approved when they are submitted. */
    val AdminApprovalRequired: kotlin.Boolean? = null
) {

}

