/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


import com.squareup.moshi.Json

/**
 * Type of invoice detail item.
 * Values: unspecified,eventRegistration,guestsNumber,guestCard,extraCost,memberLevel,prorate,discount,donation,onlineStoreProduct,onlineStoreShipping
 */
enum class OrderDetailType(val value: kotlin.String) {

    @Json(name = "Unspecified")
    unspecified("Unspecified"),

    @Json(name = "EventRegistration")
    eventRegistration("EventRegistration"),

    @Json(name = "GuestsNumber")
    guestsNumber("GuestsNumber"),

    @Json(name = "GuestCard")
    guestCard("GuestCard"),

    @Json(name = "ExtraCost")
    extraCost("ExtraCost"),

    @Json(name = "MemberLevel")
    memberLevel("MemberLevel"),

    @Json(name = "Prorate")
    prorate("Prorate"),

    @Json(name = "Discount")
    discount("Discount"),

    @Json(name = "Donation")
    donation("Donation"),

    @Json(name = "OnlineStoreProduct")
    onlineStoreProduct("OnlineStoreProduct"),

    @Json(name = "OnlineStoreShipping")
    onlineStoreShipping("OnlineStoreShipping");

}

