/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * Thhis object describes how payment is allocated among invoices.
 * @param Id Unique identifier.
 * @param Value allocated amount.
 * @param Invoice
 * @param InvoiceDate Invoice date
 * @param InvoiceNumber Invoice number.
 * @param Payment
 * @param PaymentDate Payment date
 * @param PaymentType
 * @param Refund
 * @param RefundDate Refund date
 */
data class PaymentAllocation(
    /* Unique identifier. */
    val Id: kotlin.Int? = null,
    /* allocated amount. */
    val Value: java.math.BigDecimal? = null,
    val Invoice: BundleAdministrator? = null,
    /* Invoice date */
    val InvoiceDate: java.time.LocalDateTime? = null,
    /* Invoice number. */
    val InvoiceNumber: kotlin.String? = null,
    val Payment: BundleAdministrator? = null,
    /* Payment date */
    val PaymentDate: java.time.LocalDateTime? = null,
    val PaymentType: PaymentType? = null,
    val Refund: BundleAdministrator? = null,
    /* Refund date */
    val RefundDate: java.time.LocalDateTime? = null
) {

}

