/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Defines how system manages field during renewal process. Used only by multichoice fields with an associated cost.
 * @param IncludeInRenewals Indicates if the field should be shown in renewal form.
 * @param AllowedToChangeInRenewal Indicates whether field value can be changed during renual process. Can be set to TRUE only if IncludeInRenewals is set to TRUE.
 */
data class RenewalPolicy(
    /* Indicates if the field should be shown in renewal form. */
    val IncludeInRenewals: kotlin.Boolean? = null,
    /* Indicates whether field value can be changed during renual process. Can be set to TRUE only if IncludeInRenewals is set to TRUE. */
    val AllowedToChangeInRenewal: kotlin.Boolean? = null
) {

}

