/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Url
 * @param Name Name of resource
 * @param Description Text description of the resource
 * @param AllowedOperations Collection of allowed operations for this resource. Possible values are GET - Resource can be requested POST - Resource can be created PUT - Resource can be updated DELETE - Resource can be deleted
 */
data class Resource(
    val Url: ResourceUrl,
    /* Name of resource */
    val Name: kotlin.String,
    /* Collection of allowed operations for this resource. Possible values are GET - Resource can be requested POST - Resource can be created PUT - Resource can be updated DELETE - Resource can be deleted  */
    val AllowedOperations: kotlin.Array<kotlin.String>,
    /* Text description of the resource */
    val Description: kotlin.String? = null
) {

}

