/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * Describe taxes applied to this invoice item
 * @param Amount total gross amount including all taxes
 * @param CalculatedTax1 tax 1 amount
 * @param CalculatedTax2 tax 2 amount
 * @param NetAmount net amount from invoice items
 * @param RoundedAmount rounded total amount including all taxes
 * @param Tax1
 * @param Tax2
 */
data class SalesTaxInfo(
    /* total gross amount including all taxes */
    val Amount: java.math.BigDecimal? = null,
    /* tax 1 amount */
    val CalculatedTax1: java.math.BigDecimal? = null,
    /* tax 2 amount */
    val CalculatedTax2: java.math.BigDecimal? = null,
    /* net amount from invoice items */
    val NetAmount: java.math.BigDecimal? = null,
    /* rounded total amount including all taxes */
    val RoundedAmount: java.math.BigDecimal? = null,
    val Tax1: BundleAdministrator? = null,
    val Tax2: BundleAdministrator? = null
) {

}

