/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Subject Subject of email message. May contain macros.
 * @param Body Email body in HTML format. May contain macros.
 * @param ReplyToAddress Email ReplyTo address.
 * @param ReplyToName Email ReplyTo display name.
 * @param Recipients
 * @param EventId Unique event identifier. Required if email should be sent to event-related recipients, e.g. all attendees.   See EmailRecipient description for details.
 */
data class SendEmailParams(
    /* Subject of email message. May contain macros. */
    val Subject: kotlin.String? = null,
    /* Email body in HTML format. May contain macros. */
    val Body: kotlin.String? = null,
    /* Email ReplyTo address. */
    val ReplyToAddress: kotlin.String? = null,
    /* Email ReplyTo display name. */
    val ReplyToName: kotlin.String? = null,
    val Recipients: EmailRecipients? = null,
    /* Unique event identifier. Required if email should be sent to event-related recipients, e.g. all attendees.   See EmailRecipient description for details.  */
    val EventId: kotlin.Int? = null
) {

}

