/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param RegistrationId Event registration Id.
 * @param CheckedIn Check in (true) or check out (false).
 * @param CheckedInGuests For event registrations with anonymous guests (guests as number), sets number of checked-in guests.
 */
data class CheckInParams(
    /* Event registration Id. */
    val RegistrationId: kotlin.Int,
    /* Check in (true) or check out (false). */
    val CheckedIn: kotlin.Boolean,
    /* For event registrations with anonymous guests (guests as number), sets number of checked-in guests. */
    val CheckedInGuests: kotlin.Int? = null
) {

}

