/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Id Unique field identifier.
 * @param Access
 * @param AdminOnly Indicates that the field is accessible only by administrators.
 * @param ExistsInLevels If field is defined for specific levels only, this contains list of membership levels.
 * @param MemberAccess
 * @param MemberOnly Indicates whether the field is a membership field.
 * @param IsBuiltIn The field is a built-in system field, it cannot be edited or deleted.
 * @param SupportSearch Indicates that this field can be used in $filter expression in contact search.
 * @param IsEditable Indicates that the field's value can be changed with create/update requests. Otherwise value can’t be edited through API. If non-editable field value is provided in create/update contact request, the value is ignored by API.
 * @param RulesAndTermsInfo
 * @param RenewalPolicy
 * @param ProrateInApplication If the field has associated cost, this indicates if the cost should be prorated over a partial period of time.
 * @param FieldType
 */
data class ContactFieldDescription(
    /* Field name title, could be displayed in user interface. Field name could be changed by account administrator. */
    val FieldName: kotlin.String,
    /* System-defined description of the field. Empty for custom fields. */
    val Description: kotlin.String,
    val FieldType: CustomFieldType,
    /* Unique field identifier. */
    val Id: kotlin.Int? = null,
    val Access: ContactFieldAccessLevel? = null,
    /* Indicates that the field is accessible only by administrators. */
    val AdminOnly: kotlin.Boolean? = null,
    /* If field is defined for specific levels only, this contains list of membership levels. */
    val ExistsInLevels: kotlin.Array<LinkedResource>? = null,
    val MemberAccess: MemberFieldAccess? = null,
    /* Indicates whether the field is a membership field. */
    val MemberOnly: kotlin.Boolean? = null,
    /* The field is a built-in system field, it cannot be edited or deleted. */
    val IsBuiltIn: kotlin.Boolean? = null,
    /* Indicates that this field can be used in $filter expression in contact search. */
    val SupportSearch: kotlin.Boolean? = null,
    /* Indicates that the field's value can be changed with create/update requests. Otherwise value can’t be edited through API. If non-editable field value is provided in create/update contact request, the value is ignored by API. */
    val IsEditable: kotlin.Boolean? = null,
    val RulesAndTermsInfo: RulesAndTermsInfo? = null,
    val RenewalPolicy: RenewalPolicy? = null,
    /* If the field has associated cost, this indicates if the cost should be prorated over a partial period of time. */
    val ProrateInApplication: kotlin.Boolean? = null,

    /* System-defined code associated with field. It does not change even if FieldName is edited in admin backend. */
    val SystemCode: kotlin.String? = null,
    /* Optional hint, which tells how to display and edit field. It appears for String and Choice fields. */
    val DisplayType: kotlin.String? = null,
    /* Field is system-defined and could not be deleted. However, field name could be changed by account administrator. */
    val IsSystem: kotlin.Boolean? = null,
    /* Admin-defined comment for the field. Shown as a tip when members or visitors fill in forms. */
    val FieldInstructions: kotlin.String? = null,
    /* If field value is limited to set of predefined values, this contains list of allowed values. Normally, AllowedValues appear for MultipleChoice and Choice fields. */
    val AllowedValues: kotlin.Array<OptionsListItem>? = null,
    /* Sorting order to display the field in UI */
    val Order: kotlin.Int? = null,

    val ExtraCharge: ExtraCharge? = null,
    /* Unique field identifier. */

) {

}

