/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Contact
 * @param Payment
 * @param DonationDate Donation date.
 * @param FirstName First name of the donor.
 * @param LastName Last name of the donor.
 * @param Email Email of the donor.
 * @param Organization Organization of the donor.
 * @param Phone Phone of the donor.
 * @param Comment Internal note on donation. Visible to administrators only.
 * @param PublicComment Comment on donation. Visible to both administrators and donors.
 * @param Value Donation amount.
 * @param Type
 * @param FieldValues For each custom field you have added to your Wild Apricot database, the name of the field, its system code, and its value for this donation are returned. The system code is a unique field identifier that can be used instead of the field name to identify the field. As well, a number of system fields are returned.
 */
data class Donation(
    val Contact: BundleAdministrator? = null,
    val Payment: BundleAdministrator? = null,
    /* Donation date. */
    val DonationDate: java.time.LocalDateTime? = null,
    /* First name of the donor. */
    val FirstName: kotlin.String? = null,
    /* Last name of the donor. */
    val LastName: kotlin.String? = null,
    /* Email of the donor. */
    val Email: kotlin.String? = null,
    /* Organization of the donor. */
    val Organization: kotlin.String? = null,
    /* Phone of the donor. */
    val Phone: kotlin.String? = null,
    /* Internal note on donation. Visible to administrators only. */
    val Comment: kotlin.String? = null,
    /* Comment on donation. Visible to both administrators and donors. */
    val PublicComment: kotlin.String? = null,
    /* Donation amount. */
    val Value: kotlin.Float? = null,
    val Type: DonationType? = null,
    /* For each custom field you have added to your Wild Apricot database, the name of the field, its system code, and its value for this donation are returned. The system code is a unique field identifier that can be used instead of the field name to identify the field. As well, a number of system fields are returned. */
    val FieldValues: kotlin.Array<FieldValue>? = null
) {

}

