/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Describes how email will look like when all macros are applied.
 * @param Subject Email subject with macros applied.
 * @param Body Email body HTML with mosros applied.
 */
data class EmailDraftPreview(
    /* Email subject with macros applied. */
    val Subject: kotlin.String? = null,
    /* Email body HTML with mosros applied. */
    val Body: kotlin.String? = null
) {

}

