/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Statistics related to invitees to RSVP events.
 * @param NotResponded Number of invitees who did not respond yet.
 * @param NotAttended Number of invitees who answered NO to the invite.
 * @param Attended Number of invitees who answered YES to the invite.
 * @param MaybeAttended Number of invitees who answered MAY BE to the invite.
 */
data class EventInviteeStatistics(
    /* Number of invitees who did not respond yet. */
    val NotResponded: kotlin.Int? = null,
    /* Number of invitees who answered NO to the invite. */
    val NotAttended: kotlin.Int? = null,
    /* Number of invitees who answered YES to the invite. */
    val Attended: kotlin.Int? = null,
    /* Number of invitees who answered MAY BE to the invite. */
    val MaybeAttended: kotlin.Int? = null
) {

}

