/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


import com.squareup.moshi.Json

/**
 * Control how system works with guest registrations for specific event.
 * @param Enabled Indicates if guest registrations are allowed.
 * @param CreateContactMode Indicates whether guests are automatically added to database after the main registrant confirms the registration
 */
data class EventGuestRegistrationSettings(
    /* Indicates if guest registrations are allowed. */
    val Enabled: kotlin.Boolean? = null,
    /* Indicates whether guests are automatically added to database after the main registrant confirms the registration */
    val createContactMode: EventGuestRegistrationSettings.CreateContactMode? = null
) {

    /**
     * Indicates whether guests are automatically added to database after the main registrant confirms the registration
     * Values: neverCreateContact,createContactForAllGuests,createContactForGuestsWithEmail
     */
    enum class CreateContactMode(val value: kotlin.String) {

        @Json(name = "NeverCreateContact")
        neverCreateContact("NeverCreateContact"),

        @Json(name = "CreateContactForAllGuests")
        createContactForAllGuests("CreateContactForAllGuests"),

        @Json(name = "CreateContactForGuestsWithEmail")
        createContactForGuestsWithEmail("CreateContactForGuestsWithEmail");

    }

}

