/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


import com.squareup.moshi.Json

/**
 * Describes how guests are registered. Allowed values are - Disabled - guest registration is not allowed - NumberOfGuests - number of guests should be specified. - CollectContactDetails - contact information should be collected for each guest. - CollectFullInfo - full registration info should be collected for each guest.
 * Values: disabled,numberOfGuests,collectContactDetails,collectFullInfo
 */
enum class EventGuestRegistrationPolicy(val value: kotlin.String) {

    @Json(name = "Disabled")
    disabled("Disabled"),

    @Json(name = "NumberOfGuests")
    numberOfGuests("NumberOfGuests"),

    @Json(name = "CollectContactDetails")
    collectContactDetails("CollectContactDetails"),

    @Json(name = "CollectFullInfo")
    collectFullInfo("CollectFullInfo");

}

