/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Id Unique identifier of event registration
 * @param Url
 * @param Event
 * @param Contact
 * @param RegistrationType
 * @param RegistrationTypeId Unique identifier of event registration type
 * @param GuestRegistrationsSummary
 * @param DisplayName Contact display name.
 * @param Organization Contact display name.
 * @param IsCheckedIn Indicates if registrant is already checked in for event.
 * @param RegistrationFee The fee for this registration including all extra charges and taxes.
 * @param PaidSum The sum that the registrant has already paid for the registration.
 * @param IsPaid Indicates if the registrant has already paid for the registration.
 * @param RegistrationFields A collection of registration fields values
 * @param ShowToPublic Indicates whether this registration can be shown to other event registrants.
 * @param RegistrationDate Date and time when registration was created. (Account local time)
 * @param Memo Some additional notes about this registration.
 * @param IsGuestRegistration Boolean. True if this is a guest registration, otherwise false.
 * @param OnWaitlist Indicates if event registration is in waitlist.
 * @param RecreateInvoice Optional boolean value. If specified and equals true, related invoice will be automatically updated (or created) to match selected registration type and extra cost options.
 * @param ParentRegistration
 * @param Status
 */
data class EventRegistration(
    /* Unique identifier of event registration */
    val Id: kotlin.Int,
    val Url: ResourceUrl,
    val Event: EventStub,
    val Contact: LinkedResourceWithName,
    val RegistrationType: LinkedResourceWithName,
    /* Unique identifier of event registration type */
    val RegistrationTypeId: kotlin.Int,
    /* Contact display name. */
    val DisplayName: kotlin.String,
    /* Contact display name. */
    val Organization: kotlin.String,
    /* Indicates if registrant is already checked in for event. */
    val IsCheckedIn: kotlin.Boolean,
    /* The fee for this registration including all extra charges and taxes. */
    val RegistrationFee: java.math.BigDecimal,
    /* The sum that the registrant has already paid for the registration. */
    val PaidSum: java.math.BigDecimal,
    /* Indicates if the registrant has already paid for the registration. */
    val IsPaid: kotlin.Boolean,
    /* Indicates whether this registration can be shown to other event registrants. */
    val ShowToPublic: kotlin.Boolean,
    /* Date and time when registration was created. (Account local time) */
    val RegistrationDate: kotlin.String,
    /* Boolean. True if this is a guest registration, otherwise false. */
    val IsGuestRegistration: kotlin.Boolean,
    val GuestRegistrationsSummary: GuestRegistrationsSummary? = null,
    /* A collection of registration fields values */
    val RegistrationFields: kotlin.Array<FieldValue>? = null,
    /* Some additional notes about this registration. */
    val Memo: kotlin.String? = null,
    /* Indicates if event registration is in waitlist. */
    val OnWaitlist: kotlin.Boolean? = null,
    /* Optional boolean value. If specified and equals true, related invoice will be automatically updated (or created) to match selected registration type and extra cost options. */
    val RecreateInvoice: kotlin.Boolean? = null,
    val ParentRegistration: LinkedResource? = null,
    val Status: EventRegistrationStatus? = null
) {

}

