/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


import com.squareup.moshi.Json

/**
 * This property appears for CalculatedExtraCharge fields only.
 * @param MultiplierType Indicates the type of multiplier field.   ItemPrice multiplier specifies a price for each requested item.   Percentage multiplier specifies a percent of field value to use as extra charge.
 * @param Multiplier value of multiplier for extra charge calculation
 * @param MinAmount Minimal amount of items to request (minimal field value). For ItemPrice multiplier type only.
 * @param MaxAmount Maximum amount of items to request (maximum field value). For ItemPrice multiplier type only.
 * @param MinCharge Minimal extra charge. (minimal field value). For Percentage multiplier type only.
 * @param MaxCharge Maximum extra charge. (maximum field value). For Percentage multiplier type only.
 */
data class ExtraCharge(
    /* Indicates the type of multiplier field.   ItemPrice multiplier specifies a price for each requested item.   Percentage multiplier specifies a percent of field value to use as extra charge.  */
    val multiplierType: ExtraCharge.MultiplierType,
    /* value of multiplier for extra charge calculation */
    val Multiplier: java.math.BigDecimal,
    /* Minimal amount of items to request (minimal field value). For ItemPrice multiplier type only. */
    val MinAmount: kotlin.Int? = null,
    /* Maximum amount of items to request (maximum field value). For ItemPrice multiplier type only. */
    val MaxAmount: kotlin.Int? = null,
    /* Minimal extra charge. (minimal field value). For Percentage multiplier type only. */
    val MinCharge: java.math.BigDecimal? = null,
    /* Maximum extra charge. (maximum field value). For Percentage multiplier type only. */
    val MaxCharge: java.math.BigDecimal? = null
) {

    /**
     * Indicates the type of multiplier field.   ItemPrice multiplier specifies a price for each requested item.   Percentage multiplier specifies a percent of field value to use as extra charge.
     * Values: itemPrice,percentage
     */
    enum class MultiplierType(val value: kotlin.String) {

        @Json(name = "ItemPrice")
        itemPrice("ItemPrice"),

        @Json(name = "Percentage")
        percentage("Percentage");

    }

}

