/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param Tender
 * @param Comment Internal note on payment. Visible to administrators only.
 * @param PublicComment Comment on payment. Visible to both administrators and payors.
 * @param AllocatedValue Total amount allocated to another finance documents (invoices or refunds).
 * @param RefundedAmount Amount of a refund assigned to the payment.
 * @param Type
 * @param DonationId Identifyer of Donation for payment of type DonationPayment.
 * @param FieldValues For each custom field you have added to your Wild Apricot database, the name of the field, its system code, and its value for this donation are returned. The system code is a unique field identifier that can be used instead of the field name to identify the field. As well, a number of system fields are returned.
 */
data class Payment(
    val Tender: LinkedResourceWithName? = null,
    /* Internal note on payment. Visible to administrators only. */
    val Comment: kotlin.String? = null,
    /* Comment on payment. Visible to both administrators and payors. */
    val PublicComment: kotlin.String? = null,
    /* Total amount allocated to another finance documents (invoices or refunds). */
    val AllocatedValue: kotlin.Float? = null,
    /* Amount of a refund assigned to the payment. */
    val RefundedAmount: java.math.BigDecimal? = null,
    val Type: PaymentType? = null,
    /* Identifyer of Donation for payment of type DonationPayment. */
    val DonationId: kotlin.Int? = null,
    /* For each custom field you have added to your Wild Apricot database, the name of the field, its system code, and its value for this donation are returned. The system code is a unique field identifier that can be used instead of the field name to identify the field. As well, a number of system fields are returned. */
    val FieldValues: kotlin.Array<FieldValue>? = null,
    /* Unique document identifier. */
    val Id: kotlin.Int? = null,
    val Url: ResourceUrl? = null,
    val Value: kotlin.Float? = null,
    /* Document date. */
    val DocumentDate: java.time.LocalDateTime? = null,
    val Contact: BundleAdministrator? = null,
    /* Date and time when the document was created. */
    val CreatedDate: java.time.LocalDateTime? = null,
    val CreatedBy: BundleAdministrator? = null,
    /* Date and time when the document was last modified.  Could be null. */
    val UpdatedDate: java.time.LocalDateTime? = null,
    val UpdatedBy: BundleAdministrator? = null,

    ) {

}

