/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 *
 * @param WaitlistRegistrationId Event registration Id.
 * @param EventId Event Id.
 * @param GenerateInvoice Defines if invoice should be generated in case if registration is considered paid (registration fee > 0 or any extra costs selected)
 */
data class RegisterFromWaitlistParams(
    /* Event registration Id. */
    val WaitlistRegistrationId: kotlin.Int,
    /* Event Id. */
    val EventId: kotlin.Int,
    /* Defines if invoice should be generated in case if registration is considered paid (registration fee > 0 or any extra costs selected) */
    val GenerateInvoice: kotlin.Boolean
) {

}

