/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * Taxes applied to the invoice according to account Tax Rules settings.
 * @param Name Internal account tax name.
 * @param PublicId Public tax ID (displayed on invoices).
 * @param Rate Tax rate value.
 */
data class SalesTax(
    /* Internal account tax name. */
    val Name: kotlin.String? = null,
    /* Public tax ID (displayed on invoices). */
    val PublicId: kotlin.String? = null,
    /* Tax rate value. */
    val Rate: java.math.BigDecimal? = null
) {

}

