/**
 * Wild Apricot Admin API
 *  This is Wild Apricot's API for administrators. You can use it if you already have a Wild Apricot account (typically with a website on  *.wildapricot.org). Otherwise, please use https://register.wildapricot.com to create a new account.  If you have any questions about this API, please contact our support team at support@wildapricot.com.
 *
 * OpenAPI spec version: 7.14.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 *
 * @param ContactIds
 */
data class SavedSearch(
    val ContactIds: kotlin.Array<kotlin.Int>? = null,
    /* Unique search identifier */
    val Id: kotlin.Int? = null,
    /* Saved search name */
    val Name: kotlin.String? = null,
    /* Save search description */
    val Description: kotlin.String? = null,

    ) {

}

